from . import attendance_api
from . import customer_api
from . import pitcar_queue
from . import auth
from . import cors
from . import lead_time
from . import customer_rating
from . import kpi_controller
from . import sop_controller
from . import kpi_overview
from . import lead_time_part
from . import employee_api
from . import frontoffice_api
from . import cs_sampling
from . import cs_leads_analytics
from . import cs_leads
from . import content_api
from . import mentor_request_controller
from . import session_controller
from . import tools_management
from . import mechanic_hand_tools_controller
from . import mechanic_tools_import_controller
from . import project_management_api
from . import kpi_marketing
from . import kaizen_training_api
from . import it_program_api
from . import booking_controller