from . import attendance_api
from . import customer_api
from . import pitcar_queue
from . import auth
from . import cors
from . import lead_time
from . import customer_rating
from . import kpi_controller
from . import sop_controller
from . import kpi_overview
from . import lead_time_part
from . import employee_api
from . import frontoffice_api
from . import cs_sampling
from . import cs_leads_analytics
from . import cs_leads