from . import res_users
from . import res_partner_car
from . import res_partner
from . import stock_picking
from . import account_move
from . import sale_order
from . import product_product
from . import product_tag
from . import crm_tag
from . import service_advisor
from . import project_task
from . import feedback_classification
from . import product_template
from . import queue_management
from . import queue_metric
from . import quality_metrics
from . import service_advisor_kpi
from . import service_advisor_overview
from . import mechanic_kpi
from . import mechanic_overview_kpi