from . import res_users
from . import res_partner_car
from . import res_partner
from . import stock_picking
from . import account_move
from . import sale_order
from . import product_product
from . import product_tag
from . import crm_tag
from . import service_advisor
from . import project_task
from . import feedback_classification
from . import product_template