from . import res_users
from . import res_partner_car
from . import pitcar_position
from . import res_partner
from . import stock_picking
from . import account_move
from . import sale_order
from . import sale_order_line
from . import product_product
from . import product_tag
from . import crm_tag
from . import service_advisor
from . import project_task
from . import feedback_classification
from . import product_template
from . import queue_management
from . import queue_metric
from . import quality_metrics
from . import service_advisor_kpi
from . import service_advisor_overview
from . import mechanic_kpi
from . import mechanic_overview_kpi
from . import hr_employee
from . import hr_attendance
from . import work_location
from . import sale_order_template_line
from . import sop
from . import hr_employee_public
from . import service_booking
from . import hr_working_days_config
from . import kpi_detail
from . import lead_time_part
from . import frontoffice_equipment
from . import sale_order_part_item
from . import stock_mandatory_stockout
from . import stock_audit_report
from . import cs_chat_sampling
from . import cs_leads_verification
from . import cs_contact_monitoring
from . import cs_finance_check
from . import cs_leads
from . import cs_leads_analytics
from . import content_project